<a href="https://colab.research.google.com/github/mahidhardurga/DataScience_Numpy_Practice/blob/main/numpy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy   #cmd to install numpy library

In [2]:
import numpy as np  #importing numpy library

In [3]:
my_list = [1,2,3]
n = np.array(my_list)   #converting list to array using numpy library
n

array([1, 2, 3])

In [5]:
type(my_list)   #tells the type of the variable

list

In [6]:
type(n)         #tells the type of the variable

numpy.ndarray

#Multi Dimensional Array

In [7]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])   #creating Multi Dimensional Array
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list_of_lists.shape

(3, 3)

In [10]:
np.arange(0,10)    #returns array with elements between 0,10

#np.arange(10)  same as above

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)    #returns array with elements between 0,10 with difference of 2

array([0, 2, 4, 6, 8])

In [13]:
zero = np.zeros(50)   #returns array with all elements as 0
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones((3,3))   #returns array with all elements as 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a = np.eye(5)  #returns ndarray with diagonals 1
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
mn = np.arange(0,50)  #returns array with 50 elements
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
len(mn)

50

In [21]:
mn.reshape(10,5)  #re-organise the output and will not effect/alters the original dataset

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [25]:
o = np.linspace(0,7,10)  #returns 10 evenly spaced numbers between 0,7
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [29]:
len(o)    #returns the length of the variable

10

In [30]:
o.resize(5,2)    #resize will effect/alters the orginal dataset(i.e way of displaying output will effect/alter)

In [31]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

# **Generating SomeRandom Values**

In [34]:
np.random.rand(3,2)   #create an array with given shape and populate it with random samples from a uniform distribution over [0,1]

array([[0.88146265, 0.78090969],
       [0.53618368, 0.05180279],
       [0.86379877, 0.53297427]])

In [38]:
a = np.random.randn(3,3)   #Returns a sample (or samples) from the "standard normal"  distribution
a  

array([[-1.61838842,  0.16001094, -1.10759718],
       [ 1.95600132,  0.53386754,  0.5598657 ],
       [ 0.14469919, -0.26884851,  0.34378538]])

In [41]:
#Generating 10 random integers between 4,15
mn = np.random.randint(4,15,10)   #Returns random integers from low to high
mn

array([ 6, 10, 12, 13,  8, 14,  7,  4, 13, 12])

In [42]:
mn.reshape(5,2)

array([[ 6, 10],
       [12, 13],
       [ 8, 14],
       [ 7,  4],
       [13, 12]])

In [44]:
tt = np.random.randint(4,15,(5,2))   #Returns random integers from low to high with reshape directly
tt

array([[ 5, 10],
       [10, 14],
       [11,  9],
       [ 4,  7],
       [ 7, 10]])